### ISSUE TITLE
Editorial: frozenness state section discusses discarding

### ISSUE THREAD

**Issue by domenic** [WICG/web-lifecycle#13]
This seems out of place and a bit confusing:

> In desktop Chrome, background tabs that are not important to the user (not used in some time) may be DISCARDED, to conserve memory

We're defining frozenness, but suddenly we started talking about discarding.

This probably belongs instead in file:///C:/Users/Domenic/Dropbox/GitHub/_forks/web-lifecycle/spec.html#discarded-state

**Comment by spanicker** [comment]
Moved example intervention to discarded section.
