### ISSUE TITLE
What is bfcache?

### ISSUE THREAD

**Issue by rektide** [WICG/web-lifecycle#3]
Between STOPPED and DISCARDED there is a step labeled BFCACHE. What is this step? How does it work?

**Comment by spanicker** [comment]
Sorry for the delay.
bfcache is the page cache used by some browsers to recycle pages on navigation.
See:
https://webkit.org/blog/427/webkit-page-cache-i-the-basics/

I've added a link in Further Reading section:
https://github.com/WICG/web-lifecycle/blob/master/README.md#further-reading

Feel free to reopen if you want further clarification.
